### ISSUE TITLE
Having some issues

### ISSUE THREAD

**Issue by hpompom** [robinniesert/BayesianGAS#1]
May I study your paper related to the program? Some code I can't understand. Think you !

**Comment by robinniesert** [comment]
Thanks for your interest. Here is a link to the thesis the code relates to: [https://pdfs.semanticscholar.org/7193/a8375a0eab4d48dad45be01a1f8131a6be66.pdf](https://pdfs.semanticscholar.org/7193/a8375a0eab4d48dad45be01a1f8131a6be66.pdf)

**Comment by hpompom** [comment]
Think you！

**Comment by hpompom** [comment]
Can this program make rolling prediction? I think it's important to predict VaR and ES

**Comment by robinniesert** [comment]
No I didn't look at out of sample predictive performance, so there is no code to perform rolling predictions.
